import './globals.css';

import { 
  poppinsBlack, 
  poppinsBlackItalic, 
  poppinsBold, 
  poppinsBoldItalic, 
  poppinsExtraBold, 
  poppinsExtraBoldItalic, 
  poppinsExtraLight, 
  poppinsLightItalic, 
  poppinsItalic, 
  poppinsLight, 
  poppinsExtraLightItalic, 
  poppinsMedium, 
  poppinsMediumItalic, 
  poppinsRegular, 
  poppinsSemiBold, 
  poppinsSemiBoldItalic, 
  poppinsThin, 
  poppinsThinItalic 
} 
from '@/utils/global.fonts';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`
          ${poppinsBlack.variable} 
          ${poppinsBlackItalic.variable} 
          ${poppinsBlackItalic.variable}  
          ${poppinsBold.variable} 
          ${poppinsBoldItalic.variable} 
          ${poppinsExtraBold.variable} 
          ${poppinsExtraBoldItalic.variable} 
          ${poppinsExtraLight} 
          ${poppinsLightItalic.variable} 
          ${poppinsItalic.variable} 
          ${poppinsLight.variable} 
          ${poppinsExtraLightItalic.variable} 
          ${poppinsMedium.variable} 
          ${poppinsMediumItalic.variable} 
          ${poppinsRegular.variable} 
          ${poppinsSemiBold.variable} 
          ${poppinsSemiBoldItalic.variable} 
          ${poppinsThin.variable} 
          ${poppinsThinItalic.variable}
        `}>
        {children}
      </body>
    </html>
  )
}